using ImageOrganizer.Web.CustomLogic.Definitions;
using ImageOrganizer.Web.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using Humanizer;
using Humanizer.Bytes;
using System.Text;

namespace ImageOrganizer.Web.CustomLogic
{
    public class FileHelper
    {
        public static List<string> AutoGeneratedFolders = new List<string>(new[] { AutoGenerateFolder.LIST_PREVIEW });

        public static string GetRootPath()
        {
            return ConfigurationManager.AppSettings["ImageOrganizer.RootPath"];
        }

        public static string GetAbsolutePathFromLocal(string localPath)
        {
            var rootPath = GetRootPath();
            return String.Concat(rootPath, @"\", localPath);
        }

        public static FolderInformation GetFolderInformation(string localPath = null)
        {
            var folderInformation = new FolderInformation();

            var rootPath = GetRootPath();
            folderInformation.Path = GetAbsolutePathFromLocal(localPath);
            folderInformation.BreadCrumb = PathHelper.GetBreadCrumb(folderInformation.Path);

            if (Directory.Exists(folderInformation.Path))
            {
                // Gathering information about local folders.
                // [MB]
                folderInformation.Directories = GetDirectoriesFromFolder(folderInformation.Path);

                // Gathering information about local files.
                // [MB]
                var fileList = new DirectoryInfo(folderInformation.Path).GetFiles();
                folderInformation.Files = new List<CustomFileInformation>();
                foreach (var file in fileList)
                {
                    var imageInfo = ImageHelper.GetImageInformation(file.FullName);

                    var imagePathBytes = Encoding.UTF8.GetBytes(file.FullName.Replace(rootPath, String.Empty));
                    var imagePathBase64 = Convert.ToBase64String(imagePathBytes);

                    folderInformation.Files.Add(new CustomFileInformation(imageInfo)
                    {
                        ImageHandlerPath = String.Format("/{0}/{1}", PathDefinition.LOCAL_PATH_PREFIX_IMAGE, imagePathBase64)
                    });
                }
            }

            return folderInformation;
        }

        public static List<CustomFolderInformation> GetDirectoriesFromFolder(string absolutePath)
        {
            var result = new List<CustomFolderInformation>();
            var rootPath = GetRootPath();

            var directoryList = new DirectoryInfo(absolutePath).GetDirectories();
            foreach (var directory in directoryList)
            {
                // Hide auto-gen folders.
                // [MB]
                if (AutoGeneratedFolders.Contains(directory.Name))
                {
                    continue;
                }

                result.Add(new CustomFolderInformation()
                {
                    FullName = directory.FullName,
                    Name = directory.Name,
                    LocalPath = String.Format("/{0}/{1}", PathDefinition.LOCAL_PATH_PREFIX, directory.FullName.Replace(rootPath, String.Empty))
                });
            }

            return result;
        }
    }
}